all:
	g++ -Wall -static entity.cpp game.cpp main.cpp render.cpp wall_unit.cpp screen.cpp wall.cpp game_map.cpp p_block.cpp block_unit.cpp p_square.cpp player.cpp logic_map.cpp p_lr.cpp p_line.cpp p_ll.cpp p_t.cpp p_zl.cpp p_zr.cpp -o TerminalTetris.exe
	
	